import type { Metadata } from "next";
import AdminNavbar from "@/components/layout/AdminNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <AdminNavbar />
      {children}
    </>
  );
}
