"use client"

import Image from "next/image";
import LoadingImage from "@/public/load.jpg"
import { easeInOut, motion } from "motion/react";


// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Teams App",
//   description: "Generated by create next app",
// };

const Teams = () => {
  return (
    <section className="mx-auto border border-red-200 h-screen">
      <div className="grid grid-cols-3 gap-3 ">
        <motion.div
          initial={{ opacity: 0, y: 40,scale:1 }}
          animate={{opacity:1,y:0,scale:1}}
          whileHover={{ scale: 1.1,}}
          transition={{ duration: 0.2, ease: easeInOut }}
          whileTap={{scale:0.7}}
          className="bg-white rounded-lg shadow-md p-6 hover:shadow-lg hover:translate-y-2 transition-all duration-300 flex-1 min-w-[30%]">
          <motion.div
            whileHover={{ rotate: 360 }}
            transition={{duration:0.6,ease:easeInOut}}
            className="w-24 h-24 bg-blue-200 rounded-full mx-auto flex items-center justify-center">
            <Image
              src="/image.jpg"
              width={500}
              height={500}
              alt="Global Team"
              className="w-full h-full rounded-full object-cover"
            />
          </motion.div>
        </motion.div>
        <div className="bg-white rounded-lg shadow-md hover:shadow-lg hover:translate-y-2 transition-all duration-300 flex-1 min-w-[30%]">
          <div className="w-full h-full bg-blue-200 rounded-full mx-auto flex items-center justify-center relative">
            <Image
              src="/image.jpg"
              alt="Global Team"
              className=" object-cover "
              fill={true}
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
            />
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md hover:shadow-lg hover:translate-y-2 transition-all duration-300  flex-1 min-w-[30%]">
          <div className="w-full h-full bg-blue-200 rounded-full mx-auto flex items-center justify-center relative">
            <Image
              src={LoadingImage}
              alt="Global Team"
              className=" object-cover "
              fill={true}
              priority={false}
              quality={75}
              placeholder="blur"
              blurDataURL=""
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
            />
          </div>
        </div>
      </div>
    </section>
  );
};

export default Teams;
