import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About App",
  description: "Generated by create next app",
};

export default function AboutLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <>
      <h1>hello About Layout</h1>
      {children}
    </>
  );
}
